# Numpy: Foundations
**What you'll learn in this notebook:**
1. What NumPy is 
2. Installing and importing NumPy
3. Python lists vs NumPy arrays
4. Why NumPy is faster than pure Python
5. Creating arrays
6. Array properties: shape, dtype, ndim, size
7. first practical exercises

**How to use this notebook:**
- Read each markdown cell, then run the code cell below it (Shift + Enter)
- **Modify the code and re-run** — that's how concepts stick
- Don't skip the exercises at the end — they're the test of whether it actually clicked

**Prerequisite:** Basic Python (variables, lists, loops, functions). If you've done the OOP notebook, you're more than ready.


## What is NumPy?

### The short answer

**NumPy** (Numerical Python) is a library that gives Python the ability to do fast math on large amounts of numerical data — like a calculator that can handle millions of numbers at once. NumPy is the fundamental package for scientific computing in Python.

### The longer answer

Python's built-in `list` is flexible but slow for numerical work. NumPy provides a new data structure — the **ndarray** (N-dimensional array) — that is:

- **Fast** — operations run in optimized C code under the hood
- **Memory-efficient** — stores numbers in contiguous memory blocks
- **Multi-dimensional** — handles 1D vectors, 2D matrices, 3D tensors, and beyond
- **Universal** — virtually every Python data/AI library uses NumPy arrays as its base

### Real-world uses

| Domain | Example use |
|---|---|
| Machine Learning | Storing training data, weights, gradients |
| Image Processing | Each image is a 3D array (height × width × color) |
| Data Science | Numerical columns in pandas DataFrames are NumPy arrays |
| Scientific Research | Physics simulations, signal processing, statistics |
| Finance | Time series, risk calculations, portfolio analytics |
| Cybersecurity | Feature vectors for ML-based threat detection |

### Why it was created

NumPy was born in 2005 (originally as a merger of `Numeric` and `Numarray`). Travis Oliphant created it to give Python a serious numerical computing tool — one that could compete with MATLAB and R for scientific work.

It worked. Today NumPy is downloaded **over 200 million times per month** and powers nearly every Python AI/ML library.

## Installing and Importing NumPy

### Installation

If you're using Anaconda or Google Colab, NumPy is **already installed**.

Otherwise, in your terminal:

```bash
pip install numpy
```

### Importing

There's a universal convention every Python programmer follows:

```python
import numpy as np
```

The `np` alias is so standard that using anything else marks you as a beginner. Always use `np`.

Let's verify NumPy is installed and check the version.

In [ ]:
import numpy as np

print("NumPy version:", np.__version__)
print("Where it's installed:", np.__file__)

If you see a version number, you're ready. If you got `ModuleNotFoundError`, install it with `pip install numpy` and restart the kernel.

## Python Lists vs NumPy Arrays

This is the heart of why NumPy matters. Let's compare them directly.

### Creating both

In [2]:
# A Python list
py_list = [1, 2, 3, 4, 5]

# A NumPy array — same numbers, different type
np_array = np.array([1, 2, 3, 4, 5])

print("Python list:", py_list, type(py_list))
print("NumPy array:", np_array, type(np_array))

Python list: [1, 2, 3, 4, 5] <class 'list'>
NumPy array: [1 2 3 4 5] <class 'numpy.ndarray'>


They look similar when printed, but they behave very differently. Watch what happens when we try math:

In [3]:
# Try to multiply each element by 2

# Python list: doesn't do what you'd expect
py_list_times_2 = py_list * 2
print("Python list * 2:", py_list_times_2)

# NumPy array: actually multiplies each element
np_array_times_2 = np_array * 2
print("NumPy array * 2:", np_array_times_2)

Python list * 2: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
NumPy array * 2: [ 2  4  6  8 10]



- `py_list * 2` **duplicates** the list — `[1,2,3,4,5,1,2,3,4,5]`
- `np_array * 2` **multiplies each element** by 2 — `[2,4,6,8,10]`

This is called **vectorization** — applying operations to entire arrays at once.

In [4]:
# More vectorized operations on NumPy arrays

print("Add 10 to each:", np_array + 10)
print("Square each:    ", np_array ** 2)
print("Square root:    ", np.sqrt(np_array))
print("Greater than 3: ", np_array > 3)

Add 10 to each: [11 12 13 14 15]
Square each:     [ 1  4  9 16 25]
Square root:     [1.         1.41421356 1.73205081 2.         2.23606798]
Greater than 3:  [False False False  True  True]


To do the same with a list, you'd need a loop:

In [5]:
# What you'd have to do with a list — verbose and slow
result = []
for x in py_list:
    result.append(x ** 2)
print("List squared (with loop):", result)

# vs the NumPy way
print("Array squared (one line):", np_array ** 2)

List squared (with loop): [1, 4, 9, 16, 25]
Array squared (one line): [ 1  4  9 16 25]


## Why NumPy is Faster

NumPy isn't just more concise, it's also enormously faster. 
We'll square every number from 0 to 999,999 using both approaches and time them.

In [6]:
import time

# Setup: a million numbers
N = 1_000_000
py_list = list(range(N))
np_array = np.arange(N)

# Time the Python list approach
start = time.time()
py_result = [x ** 2 for x in py_list]
py_time = time.time() - start

# Time the NumPy approach
start = time.time()
np_result = np_array ** 2
np_time = time.time() - start

print(f"Python list took: {py_time:.4f} seconds")
print(f"NumPy array took: {np_time:.4f} seconds")
print(f"NumPy is {py_time / np_time:.1f}x faster")

Python list took: 0.2489 seconds
NumPy array took: 0.0024 seconds
NumPy is 102.1x faster


You'll typically see NumPy run **20 to 100 times faster** than pure Python for these kinds of operations. On larger datasets, the gap grows even more.

### Why the huge difference?

Three reasons:

1. **Contiguous memory** — NumPy arrays store all values in one tightly packed block of memory. Python lists store pointers to scattered objects, causing slow memory access.

2. **Fixed data types** — every element in a NumPy array has the same type (e.g., all `int32`). Python lists let each item be any type, requiring type checks on every operation.

3. **C under the hood** — NumPy's operations are written in C and run as compiled machine code. Python is interpreted, which is much slower.

In short: NumPy gives you C-level performance while you write Python-level code.

### Visual: how memory layout differs

```
Python list  →  [ ptr ][ ptr ][ ptr ][ ptr ][ ptr ]
                  ↓     ↓     ↓     ↓     ↓
                 int   int   int   int   int    (scattered in memory)

NumPy array  →  [ 1 ][ 2 ][ 3 ][ 4 ][ 5 ]      (contiguous block)
```

This is why NumPy can process millions of numbers in milliseconds while Python lists take seconds.

## Creating Arrays — All the Methods You'll Actually Use

There are many ways to create NumPy arrays. Here are the ones that come up in real code.

### Method 1: From a Python list (`np.array`)

The most direct way — pass any list (or list of lists).

In [7]:
# 1D array (vector)
a = np.array([10, 20, 30, 40, 50])
print("1D:", a)

# 2D array (matrix) — list of lists
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print("2D:")
print(b)

# 3D array (tensor) — list of lists of lists
c = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]]])
print("3D:")
print(c)

1D: [10 20 30 40 50]
2D:
[[1 2 3]
 [4 5 6]]
3D:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Method 2: Pre-filled arrays (`zeros`, `ones`, `full`)

When you need an array of a specific shape filled with a specific value.

In [8]:
# All zeros — common starting point
print("Zeros (1D):", np.zeros(5))
print("Zeros (2D):")
print(np.zeros((3, 4)))  # 3 rows, 4 columns

# All ones
print("\nOnes:")
print(np.ones((2, 3)))

# Custom fill value
print("\nFilled with 7:")
print(np.full((2, 3), 7))

Zeros (1D): [0. 0. 0. 0. 0.]
Zeros (2D):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones:
[[1. 1. 1.]
 [1. 1. 1.]]

Filled with 7:
[[7 7 7]
 [7 7 7]]


### Method 3: Ranges (`arange`, `linspace`)

For sequences of numbers — very common.

In [9]:
# arange: like Python's range(), but returns an array
print("0 to 9:        ", np.arange(10))
print("5 to 14:       ", np.arange(5, 15))
print("0 to 20 by 2:  ", np.arange(0, 21, 2))

# linspace: N evenly-spaced numbers between start and stop
print("\n5 numbers from 0 to 1:", np.linspace(0, 1, 5))
print("11 numbers from 0 to 100:", np.linspace(0, 100, 11))

0 to 9:         [0 1 2 3 4 5 6 7 8 9]
5 to 14:        [ 5  6  7  8  9 10 11 12 13 14]
0 to 20 by 2:   [ 0  2  4  6  8 10 12 14 16 18 20]

5 numbers from 0 to 1: [0.   0.25 0.5  0.75 1.  ]
11 numbers from 0 to 100: [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


**When to use which?**
- `arange(start, stop, step)` — when you know the step size
- `linspace(start, stop, num)` — when you want exactly N points evenly spaced

A common gotcha with `arange`: floating-point steps can be imprecise (`np.arange(0, 1, 0.1)` may not include all expected values). For floats, prefer `linspace`.

### Method 4: Random arrays

Used everywhere in ML for initialization, sampling, simulations.

In [10]:
# Set a seed so results are reproducible
np.random.seed(42)

# Random floats between 0 and 1
print("Uniform [0, 1):")
print(np.random.rand(3, 4))

# Random integers
print("\nRandom ints 0-99:")
print(np.random.randint(0, 100, size=(2, 5)))

# Random samples from a normal distribution (mean=0, std=1)
print("\nStandard normal:")
print(np.random.randn(3))

Uniform [0, 1):
[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]

Random ints 0-99:
[[29 37  1 63 59]
 [20 32 75 57 21]]

Standard normal:
[-2.43910582  0.60344123 -0.25104397]


### Method 5: Identity and special matrices

In [12]:
# Identity matrix (1s on the diagonal, 0s elsewhere)
print("3x3 identity:")
print(np.eye(3))

# Diagonal matrix from a list
print("\nDiagonal matrix:")
print(np.diag([1, 2, 3, 4]))

# Empty array (uninitialized memory — fast but values are garbage)
# Useful when you'll fill it immediately
print("\nEmpty 2x3 (don't trust the values):")
print(np.empty((2, 3)))

3x3 identity:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Diagonal matrix:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

Empty 2x3 (don't trust the values):
[[1. 1. 1.]
 [1. 1. 1.]]


## Array Properties — Knowing What You Have

Every NumPy array has metadata you can inspect. These four properties come up constantly:

| Property | What it tells you |
|---|---|
| `.shape` | Dimensions as a tuple (rows, columns, ...) |
| `.ndim`  | Number of dimensions (1, 2, 3, ...) |
| `.size`  | Total number of elements |
| `.dtype` | Data type of the elements |

In [13]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

print("Array:")
print(a)
print()
print(f"shape: {a.shape}    → 3 rows × 4 columns")
print(f"ndim:  {a.ndim}        → 2D array (matrix)")
print(f"size:  {a.size}       → 12 total elements")
print(f"dtype: {a.dtype}    → 64-bit integers")

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

shape: (3, 4)    → 3 rows × 4 columns
ndim:  2        → 2D array (matrix)
size:  12       → 12 total elements
dtype: int32    → 64-bit integers


### Understanding shape

The `shape` tuple tells you the size of each dimension:

- `(5,)` — 1D array with 5 elements (a vector)
- `(3, 4)` — 2D array with 3 rows and 4 columns (a matrix)
- `(2, 3, 4)` — 3D array: 2 layers, each 3×4


In [14]:
# Compare shapes
vec   = np.array([1, 2, 3, 4, 5])
mat   = np.array([[1, 2], [3, 4], [5, 6]])
cube  = np.zeros((2, 3, 4))

print(f"vec  shape: {vec.shape}     ndim: {vec.ndim}")
print(f"mat  shape: {mat.shape}    ndim: {mat.ndim}")
print(f"cube shape: {cube.shape}  ndim: {cube.ndim}")

vec  shape: (5,)     ndim: 1
mat  shape: (3, 2)    ndim: 2
cube shape: (2, 3, 4)  ndim: 3


## Data Types (dtype)

Unlike Python lists, every element in a NumPy array shares the **same data type**. This is what makes NumPy fast.
### Common dtypes

| dtype | Description | Range / use |
|---|---|---|
| `int8`, `int16`, `int32`, `int64` | Signed integers | Whole numbers (default is int64 on 64-bit systems) |
| `uint8`, `uint16`, `uint32`, `uint64` | Unsigned integers | Non-negative — `uint8` is used for image pixels (0-255) |
| `float16`, `float32`, `float64` | Floating point | Decimal numbers (default is float64) |
| `bool` | Boolean | True/False |
| `complex64`, `complex128` | Complex numbers | a + bj |
| `str_`, `object` | Text or arbitrary | Rarely used — defeats NumPy's speed |

In [16]:
# NumPy picks a dtype automatically
int_array   = np.array([1, 2, 3])
float_array = np.array([1.0, 2.0, 3.0])
mixed_array = np.array([1, 2, 3.5])     # presence of a float promotes all to float

print(f"int_array dtype:   {int_array.dtype}")
print(f"float_array dtype: {float_array.dtype}")
print(f"mixed_array dtype: {mixed_array.dtype}")
print(f"mixed_array:       {mixed_array.dtype}")

int_array dtype:   int32
float_array dtype: float64
mixed_array dtype: float64
mixed_array:       float64


In [17]:
# Specify dtype explicitly
a = np.array([1, 2, 3], dtype=np.float32)
print(f"a:     {a}")
print(f"dtype: {a.dtype}")

# Convert with .astype()
b = a.astype(np.int32)
print(f"\nb (after astype):  {b}")
print(f"dtype: {b.dtype}")

a:     [1. 2. 3.]
dtype: float32

b (after astype):  [1 2 3]
dtype: int32


### Common bug: integer overflow

If your dtype is too small for the values, NumPy **silently wraps around**. No error, just wrong answers.

In [19]:
# uint8 only holds 0-255. What happens at 256?
small = np.array([250, 254], dtype=np.uint8)
print("Original:", small)

result = small + 10  # 260 and 264 — both overflow!
print("After +10:", result)
print("Values silently wrapped! 260 became", result[0])

Original: [250 254]
After +10: [4 8]
Values silently wrapped! 260 became 4


**Lesson:** when in doubt, use `int64` or `float64` (the defaults). Only use smaller dtypes when you're sure of the range OR you need to save memory.

## A Few More Foundational Operations


### Accessing elements 

In [21]:
a = np.array([10, 20, 30, 40, 50])

print("First element:", a[0])
print("Last element: ", a[-1])
print("First three:  ", a[:3])

# 2D access uses [row, col]
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(f"\nb[0, 1] = {b[0, 1]}  → row 0, col 1")
print(f"b[1, 2] = {b[1, 2]}  → row 1, col 2")

First element: 10
Last element:  50
First three:   [10 20 30]

b[0, 1] = 2  → row 0, col 1
b[1, 2] = 6  → row 1, col 2


### Quick aggregations

In [22]:
nums = np.array([5, 10, 15, 20, 25, 30])

print(f"Sum:     {nums.sum()}")
print(f"Mean:    {nums.mean()}")
print(f"Min:     {nums.min()}")
print(f"Max:     {nums.max()}")
print(f"Std dev: {nums.std():.2f}")

Sum:     105
Mean:    17.5
Min:     5
Max:     30
Std dev: 8.54


### Reshaping

In [23]:
# Reshape a 1D array of 12 elements into 3x4
flat = np.arange(12)
print("Flat:", flat)
print(f"Shape: {flat.shape}")

matrix = flat.reshape(3, 4)
print("\nReshaped to 3x4:")
print(matrix)
print(f"Shape: {matrix.shape}")

Flat: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)

Reshaped to 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4)


## Practice Exercises

The only way NumPy clicks is by writing it. Try these without looking at the answers. The solutions are below each one — but resist peeking.

### Exercise 1
Create a NumPy array containing the numbers from 10 to 50 (inclusive). What is its `shape`, `size`, and `dtype`?

### Exercise 2
Create a 4×4 matrix where every element is the number 7. Print it.

### Exercise 3
Create an array of 20 evenly-spaced numbers between -1 and 1. Print the first 5 and last 5 values.

### Exercise 4
Without using a loop, create an array `nums = [1, 2, 3, 4, 5]` and compute:
- The cube of each element
- The values where `nums > 2` (boolean array)
- The sum of all elements
- The mean of all elements

### Exercise 5 (challenge)
Create a 5×5 identity matrix, multiply it by 3, and find the sum of all elements. Predict the answer before running the code.

In [24]:
# Exercise 1
arr = np.arange(10, 51)
print("Array:", arr)
print(f"shape: {arr.shape}")
print(f"size:  {arr.size}")
print(f"dtype: {arr.dtype}")

Array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
shape: (41,)
size:  41
dtype: int32


In [25]:
# Exercise 2
m = np.full((4, 4), 7)
print(m)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [26]:
# Exercise 3
arr = np.linspace(-1, 1, 20)
print("First 5:", arr[:5])
print("Last 5: ", arr[-5:])

First 5: [-1.         -0.89473684 -0.78947368 -0.68421053 -0.57894737]
Last 5:  [0.57894737 0.68421053 0.78947368 0.89473684 1.        ]


In [27]:
# Exercise 4
nums = np.array([1, 2, 3, 4, 5])

print("Cubed:   ", nums ** 3)
print("> 2:     ", nums > 2)
print("Sum:     ", nums.sum())
print("Mean:    ", nums.mean())

Cubed:    [  1   8  27  64 125]
> 2:      [False False  True  True  True]
Sum:      15
Mean:     3.0


In [28]:
# Exercise 5
# Prediction: identity has 5 ones on the diagonal.
# Multiply by 3 → diagonal becomes 3s.
# Sum = 5 × 3 = 15
m = np.eye(5) * 3
print(m)
print("Sum:", m.sum())

[[3. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 3.]]
Sum: 15.0
