# Numpy: Array Operations

In [ ]:
import numpy as np
print("NumPy version:", np.__version__)

## Basic Indexing

Indexing means accessing specific elements by their position. Like Python lists, but more powerful.

### 1D arrays — just like lists

In [2]:
import numpy as np
a = np.array([10, 20, 30, 40, 50])

print("a[0]  =", a[0])     # first element
print("a[2]  =", a[2])     # third element
print("a[-1] =", a[-1])    # last element
print("a[-2] =", a[-2])    # second-to-last

a[0]  = 10
a[2]  = 30
a[-1] = 50
a[-2] = 40


### 2D arrays — use `[row, col]`, not `[row][col]`

This is the most common beginner stumble. NumPy uses comma-separated indexing inside one pair of brackets.

In [ ]:
b = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])

# The NumPy way
print("b[0, 0] =", b[0, 0])     # row 0, col 0 → 1
print("b[1, 2] =", b[1, 2])     # row 1, col 2 → 7
print("b[2, -1] =", b[2, -1])   # last row, last col → 12

# Also works but slower (chained indexing creates intermediate arrays)
print("\nb[1][2] =", b[1][2])

**Always use `b[row, col]` (single brackets, comma).** It's faster and the standard convention. `b[row][col]` works but is slower for assignment and unnecessary.

## Slicing — Selecting Ranges

Slicing uses the same `start:stop:step` syntax as Python lists. The key thing to remember: **`stop` is exclusive** (not included).
Rows (::2): Takes row 0, skips row 1, takes row 2, skips row 3.

Columns (::2): Takes column 0, skips column 1, takes column 2, skips column 3.
### 1D slicing

In [4]:
a = np.arange(10)
print("a:", a)

print("\na[2:5]    =", a[2:5])      # indices 2, 3, 4
print("a[:5]     =", a[:5])         # from start to index 4
print("a[5:]     =", a[5:])         # from index 5 to end
print("a[::2]    =", a[::2])        # every other element
print("a[::-1]   =", a[::-1])       # reversed
print("a[1:8:2]  =", a[1:8:2])      # from 1 to 7, step 2

a: [0 1 2 3 4 5 6 7 8 9]

a[2:5]    = [2 3 4]
a[:5]     = [0 1 2 3 4]
a[5:]     = [5 6 7 8 9]
a[::2]    = [0 2 4 6 8]
a[::-1]   = [9 8 7 6 5 4 3 2 1 0]
a[1:8:2]  = [1 3 5 7]


### 2D slicing — slice each dimension

In [3]:
b = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12],
              [13, 14, 15, 16]])
print("b:")
print(b)

# First two rows
print("\nFirst 2 rows:")
print(b[:2])

# First two columns
print("\nFirst 2 columns:")
print(b[:, :2])

# Middle 2x2 block
print("\nMiddle 2x2 block:")
print(b[1:3, 1:3])

# Every other row, every other column
print("\nEvery other row & col:")
print(b[::2, ::2])

b:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

First 2 rows:
[[1 2 3 4]
 [5 6 7 8]]

First 2 columns:
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]

Middle 2x2 block:
[[ 6  7]
 [10 11]]

Every other row & col:
[[ 1  3]
 [ 9 11]]


### Critical gotcha: slices are VIEWS, not copies

A slice doesn't make a new array — it's a window into the original. Modifying the slice modifies the original.

In [5]:
original = np.array([1, 2, 3, 4, 5])
slice_of_it = original[1:4]
print("Before:")
print("  Original:", original)
print("  Slice:   ", slice_of_it)

# Modify the slice
slice_of_it[0] = 999

print("\nAfter changing slice[0] to 999:")
print("  Original:", original)   # ← also changed!
print("  Slice:   ", slice_of_it)

Before:
  Original: [1 2 3 4 5]
  Slice:    [2 3 4]

After changing slice[0] to 999:
  Original: [  1 999   3   4   5]
  Slice:    [999   3   4]


To get an independent copy, use `.copy()`:

In [6]:
original = np.array([1, 2, 3, 4, 5])
independent = original[1:4].copy()  # ← explicit copy

independent[0] = 999

print("Original:    ", original)
print("Independent: ", independent)
# Original is unchanged

Original:     [1 2 3 4 5]
Independent:  [999   3   4]


**Rule of thumb:** if you plan to modify a slice and DON'T want the original to change, always `.copy()`. This is one of the most common sources of bugs for NumPy beginners.

## Part 3: Boolean Masking
This is one of NumPy's most powerful features. You can select elements using a boolean condition.

### The basic idea

In [7]:
scores = np.array([45, 78, 92, 67, 88, 51, 99, 33, 71])

# A comparison returns a boolean array
mask = scores >= 70
print("Mask:", mask)

# Use the mask to select elements
print("Scores >= 70:", scores[mask])

Mask: [False  True  True False  True False  True False  True]
Scores >= 70: [78 92 88 99 71]


You can combine the two steps:

In [ ]:
scores = np.array([45, 78, 92, 67, 88, 51, 99, 33, 71])

print("Passing scores:", scores[scores >= 70])
print("Failing scores:", scores[scores < 70])
print("Top scores:    ", scores[scores >= 90])

### Combining conditions with `&` (and), `|` (or), `~` (not)

 You **MUST** use `&` / `|` / `~`, NOT `and` / `or` / `not`. And **wrap each condition in parentheses**.

In [8]:
scores = np.array([45, 78, 92, 67, 88, 51, 99, 33, 71])

# Between 60 and 90
mid = scores[(scores >= 60) & (scores <= 90)]
print("Between 60 and 90:", mid)

# Below 50 OR above 90
extremes = scores[(scores < 50) | (scores > 90)]
print("Extremes:         ", extremes)

# NOT passing
failing = scores[~(scores >= 70)]
print("Not passing:      ", failing)

Between 60 and 90: [78 67 88 71]
Extremes:          [45 92 99 33]
Not passing:       [45 67 51 33]


### Using masks to modify values

In [9]:
data = np.array([1, -2, 3, -4, 5, -6, 7])
print("Original:", data)

# Replace all negative values with 0
data[data < 0] = 0
print("Clamped: ", data)

Original: [ 1 -2  3 -4  5 -6  7]
Clamped:  [1 0 3 0 5 0 7]


In [10]:
# np.where: vectorized if/else
temps = np.array([15, 32, 28, 5, 22, 38, -2])

# If temp >= 25, label "hot", else "cool"
labels = np.where(temps >= 25, "hot", "cool")
print("Temps:  ", temps)
print("Labels: ", labels)

# np.where with numbers (clip values)
clipped = np.where(temps < 0, 0, temps)
print("Clipped:", clipped)

Temps:   [15 32 28  5 22 38 -2]
Labels:  ['cool' 'hot' 'hot' 'cool' 'cool' 'hot' 'cool']
Clipped: [15 32 28  5 22 38  0]


## Fancy Indexing — Picking Specific Positions

Use an array of indices to pick non-contiguous elements.

In [11]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])

# Pick elements at indices 0, 3, and 6
picks = a[[0, 3, 6]]
print("Picked:", picks)

# Pick the same element multiple times
repeats = a[[0, 0, 2, 2, 4]]
print("With repeats:", repeats)

Picked: [10 40 70]
With repeats: [10 10 30 30 50]


In [12]:
# 2D fancy indexing — pick specific (row, col) pairs
b = np.array([[ 1,  2,  3],
              [ 4,  5,  6],
              [ 7,  8,  9],
              [10, 11, 12]])

# Pick (0,0), (1,1), (2,2), (3,0)
rows = [0, 1, 2, 3]
cols = [0, 1, 2, 0]
result = b[rows, cols]
print("Selected:", result)  # 1, 5, 9, 10

Selected: [ 1  5  9 10]


## Reshaping — Changing Dimensions

You can reshape an array as long as the total number of elements stays the same.

In [13]:
# Start with 12 elements
flat = np.arange(12)
print("Flat (shape", flat.shape, "):")
print(flat)

# Reshape to 3x4
m1 = flat.reshape(3, 4)
print("\n3x4 (shape", m1.shape, "):")
print(m1)

# Reshape to 4x3
m2 = flat.reshape(4, 3)
print("\n4x3 (shape", m2.shape, "):")
print(m2)

# Reshape to 2x2x3 (3D)
m3 = flat.reshape(2, 2, 3)
print("\n2x2x3 (shape", m3.shape, "):")
print(m3)

Flat (shape (12,) ):
[ 0  1  2  3  4  5  6  7  8  9 10 11]

3x4 (shape (3, 4) ):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

4x3 (shape (4, 3) ):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

2x2x3 (shape (2, 2, 3) ):
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


### Use `-1` to mean "figure it out"

You can put `-1` for ONE dimension and NumPy will compute it.

In [14]:
flat = np.arange(24)

# "I want 4 rows; compute columns automatically"
m = flat.reshape(4, -1)
print("Shape with reshape(4, -1):", m.shape)

# "I want 3 columns; compute rows automatically"
m = flat.reshape(-1, 3)
print("Shape with reshape(-1, 3):", m.shape)

# Flatten back to 1D using -1
back_to_flat = m.reshape(-1)
print("Flattened back:", back_to_flat.shape)

Shape with reshape(4, -1): (4, 6)
Shape with reshape(-1, 3): (8, 3)
Flattened back: (24,)


### `flatten()` vs `ravel()` — both flatten to 1D, with one difference

In [15]:
m = np.array([[1, 2, 3],
              [4, 5, 6]])

# flatten() always returns a COPY
f1 = m.flatten()

# ravel() returns a VIEW when possible (faster, but watch out)
f2 = m.ravel()

print("flatten():", f1)
print("ravel():  ", f2)

# Modify the ravel result — affects the original
f2[0] = 999
print("\nAfter f2[0] = 999:")
print("m:", m)        # ← changed!
print("f1:", f1)      # ← unchanged (was a copy)

flatten(): [1 2 3 4 5 6]
ravel():   [1 2 3 4 5 6]

After f2[0] = 999:
m: [[999   2   3]
 [  4   5   6]]
f1: [1 2 3 4 5 6]


**Rule:** use `flatten()` when you need a safe copy. Use `ravel()` when you want speed and don't care about views.

### Transposing — flipping rows and columns

In [16]:
m = np.array([[1, 2, 3],
              [4, 5, 6]])
print("Original shape:", m.shape)
print(m)

# Two equivalent ways to transpose
print("\nTransposed (.T):")
print(m.T)
print("Shape:", m.T.shape)

Original shape: (2, 3)
[[1 2 3]
 [4 5 6]]

Transposed (.T):
[[1 4]
 [2 5]
 [3 6]]
Shape: (3, 2)


## Broadcasting — NumPy's Secret Weapon

Broadcasting lets you do operations between arrays of **different shapes** without writing loops. It's possibly the most powerful NumPy feature.

### The simplest case: array + scalar

In [17]:
a = np.array([1, 2, 3, 4, 5])

# Add a scalar to every element
print(a + 10)
print(a * 2)
print(a ** 2)

[11 12 13 14 15]
[ 2  4  6  8 10]
[ 1  4  9 16 25]


The scalar "10" is *broadcast* across the array. NumPy doesn't actually create `[10, 10, 10, 10, 10]` — it cleverly pretends to.

### Array + array of compatible shapes

In [18]:
# A 3x4 matrix
m = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# A 1D array with 4 elements — same number as columns
row_vec = np.array([10, 20, 30, 40])

# Broadcasting: row_vec is added to EVERY row
print("m + row_vec:")
print(m + row_vec)

m + row_vec:
[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]


In [ ]:
# A column vector (shape (3, 1)) broadcasts across COLUMNS
col_vec = np.array([[100],
                    [200],
                    [300]])
print("Shape of col_vec:", col_vec.shape)

print("\nm + col_vec (added to each column):")
print(m + col_vec)

### The broadcasting rules

For two arrays to broadcast together, compare their shapes **right-aligned**:

```
m.shape       = (3, 4)
row_vec.shape =    (4,)        ← right-aligned

Step 1: Align right
m       (3, 4)
row_vec (   4)

Step 2: Pad with 1s on the left
m       (3, 4)
row_vec (1, 4)

Step 3: Two shapes are compatible if, for each dimension:
   - they are equal, OR
   - one of them is 1
```

Both dimensions check out: `(3,4)` vs `(1,4)` → broadcasts to `(3,4)`.

In [19]:
# Practical example: normalize rows of a matrix
data = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])

# Compute the mean of each row → shape (3,)
row_means = data.mean(axis=1)
print("Row means:", row_means)

# To subtract row means from each row, we need to reshape (3,) → (3, 1)
row_means_col = row_means.reshape(-1, 1)
print("\nReshaped to column:", row_means_col.shape)

# Now broadcasting works: (3,3) - (3,1)
centered = data - row_means_col
print("\nCentered:")
print(centered)

Row means: [20. 50. 80.]

Reshaped to column: (3, 1)

Centered:
[[-10.   0.  10.]
 [-10.   0.  10.]
 [-10.   0.  10.]]


### When broadcasting FAILS

If shapes can't be aligned, you get a ValueError. Read the error message — it tells you exactly which shapes didn't match.

In [20]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])           # shape (2, 3)
b = np.array([10, 20])              # shape (2,) — wrong!

try:
    result = a + b
except ValueError as e:
    print("Error:", e)
    print("\nThe issue: a is (2,3), b is (2,). Right-aligned: (2,3) vs (2,) ← 3 ≠ 2")
    print("Fix: reshape b to (2, 1) so it broadcasts down the rows")

# Fix
b_fixed = b.reshape(-1, 1)
print("\nWith reshape:")
print(a + b_fixed)

Error: operands could not be broadcast together with shapes (2,3) (2,) 

The issue: a is (2,3), b is (2,). Right-aligned: (2,3) vs (2,) ← 3 ≠ 2
Fix: reshape b to (2, 1) so it broadcasts down the rows

With reshape:
[[11 12 13]
 [24 25 26]]


## Stacking and Splitting

Combining multiple arrays or breaking one apart.

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack vertically (rows on top of each other)
v = np.vstack([a, b])
print("vstack:")
print(v)

# Stack horizontally (side by side)
h = np.hstack([a, b])
print("\nhstack:", h)

# Concatenate is the general version
c = np.concatenate([a, b])
print("concatenate:", c)

vstack:
[[1 2 3]
 [4 5 6]]

hstack: [1 2 3 4 5 6]
concatenate: [1 2 3 4 5 6]


In [22]:
# For 2D, vstack and hstack work along different axes
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

print("Original m1:")
print(m1)
print("\nvstack (stack rows):")
print(np.vstack([m1, m2]))
print("\nhstack (stack columns):")
print(np.hstack([m1, m2]))

Original m1:
[[1 2]
 [3 4]]

vstack (stack rows):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

hstack (stack columns):
[[1 2 5 6]
 [3 4 7 8]]


In [23]:
# Splitting
a = np.arange(12)
print("Original:", a)

# Split into 3 equal parts
parts = np.split(a, 3)
print("\nSplit into 3 parts:")
for i, p in enumerate(parts):
    print(f"  Part {i}: {p}")

# Split at specific indices
parts = np.split(a, [3, 7])  # split before index 3, before index 7
print("\nSplit at [3, 7]:")
for i, p in enumerate(parts):
    print(f"  Part {i}: {p}")

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Split into 3 parts:
  Part 0: [0 1 2 3]
  Part 1: [4 5 6 7]
  Part 2: [ 8  9 10 11]

Split at [3, 7]:
  Part 0: [0 1 2]
  Part 1: [3 4 5 6]
  Part 2: [ 7  8  9 10 11]


## Practice Exercises

### Exercise 1
Create a 5×5 matrix containing the numbers 1 through 25. Then extract:
- The middle row
- The middle column
- The center 3×3 block

### Exercise 2
You have an array `arr = np.array([3, 7, 1, 9, 4, 6, 2, 8, 5])`. Without using a loop:
- Find all values greater than 5
- Replace all values less than 4 with 0 (modify in place)

### Exercise 3
Create a 1D array of 16 random integers between 0 and 100. Reshape it into a 4×4 matrix. Find:
- The maximum value of each row
- The minimum value of each column
- The overall mean

### Exercise 4 (broadcasting)
You have a 3×4 matrix of test scores (3 students × 4 tests):
```
scores = np.array([[80, 75, 90, 85],
                   [60, 70, 65, 75],
                   [95, 88, 92, 98]])
```
- Compute each student's average (axis=1)
- Subtract each student's average from their scores so the rows are mean-centered

### Exercise 5 (challenge)
Create an 8×8 chessboard pattern (alternating 0s and 1s) WITHOUT using any loops. Hint: think about which rows and columns get which values.

In [24]:
# Exercise 1
m = np.arange(1, 26).reshape(5, 5)
print("Matrix:")
print(m)
print("\nMiddle row:", m[2])
print("Middle col:", m[:, 2])
print("\nCenter 3x3:")
print(m[1:4, 1:4])

Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Middle row: [11 12 13 14 15]
Middle col: [ 3  8 13 18 23]

Center 3x3:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [25]:
# Exercise 2
arr = np.array([3, 7, 1, 9, 4, 6, 2, 8, 5])

print("Greater than 5:", arr[arr > 5])

arr[arr < 4] = 0
print("After replacement:", arr)

Greater than 5: [7 9 6 8]
After replacement: [0 7 0 9 4 6 0 8 5]


In [26]:
# Exercise 3
np.random.seed(0)
arr = np.random.randint(0, 101, 16)
print("Random 1D:", arr)

m = arr.reshape(4, 4)
print("\nReshaped:")
print(m)

print("\nMax of each row: ", m.max(axis=1))
print("Min of each col: ", m.min(axis=0))
print(f"Overall mean:    {m.mean():.2f}")

Random 1D: [44 47 64 67 67  9 83 21 36 87 70 88 88 12 58 65]

Reshaped:
[[44 47 64 67]
 [67  9 83 21]
 [36 87 70 88]
 [88 12 58 65]]

Max of each row:  [67 83 88 88]
Min of each col:  [36  9 58 21]
Overall mean:    56.62


In [27]:
# Exercise 4
scores = np.array([[80, 75, 90, 85],
                   [60, 70, 65, 75],
                   [95, 88, 92, 98]])

avgs = scores.mean(axis=1)
print("Student averages:", avgs)

# Reshape avgs to (3, 1) so it broadcasts across columns
centered = scores - avgs.reshape(-1, 1)
print("\nMean-centered scores:")
print(centered)

Student averages: [82.5  67.5  93.25]

Mean-centered scores:
[[-2.5  -7.5   7.5   2.5 ]
 [-7.5   2.5  -2.5   7.5 ]
 [ 1.75 -5.25 -1.25  4.75]]


In [28]:
# Exercise 5 — chessboard
# Approach: a cell at (i, j) is 1 if (i + j) is odd, else 0

# np.indices returns row and col index grids
rows, cols = np.indices((8, 8))
board = (rows + cols) % 2
print(board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
